export const APP = {
  title: "Vivid Frozen Foods & Drinks",
  name: "Vivid Foods",
  slug: "vivid-foods",
  copyright: "&copy; 2025 Vivid Foods by HWP Labs. All rights reserved.",
  theme: {
    brand: "#7C3AED",
    contrast: "#10B981",
    accentPink: "#F472B6",
    accentYellow: "#FBBF24",
    successContainer: "#C8E6C9",
    success: "#10b981",
    dangerContainer: "#FCE7E6",
    danger: "#f472b6",
    warningContainer: "#FCE7E6",
    warning: "#fbbf24",
  },
  accessTokenKey: "vivid_access_token",
  refreshTokenKey: "vivid_refresh_token",
  localStorageKey: "vivid_local_storage",
};
